// @generated by protoc-gen-repo — DO NOT EDIT.
// A GENERATED repository that does not extend BaseRepository. It matches the
// class glob (src/repos/*.repository.ts) but MUST be excluded from the census
// (codegen output must never inflate/deflate the conformance count) — so N
// stays 5 and this file is neither a conformer nor a deviant.
export class ProtoRepository {
  raw(): unknown {
    return null;
  }
}
