#!/usr/bin/env python3
"""exclusion_pass.py — DeepInit's deterministic pre-scan file filter (the executable reference).

The in-skill spec is `skills/deep-init/references/detection.md` -> "Exclusion pass (deterministic — runs BEFORE
every layer)". This is its runnable, testable form (the same pattern as `graphify_adapter.py`): build
the candidate file set ONCE so the SAME filtered set feeds scc / Graphify / ctags / grep, and COUNT
every exclusion (a silent skip reads as "analyzed and clean" when it wasn't — global-rules R8).

Honesty taxonomy (returned + the harness §41 gate asserts it):
  {gitignored, vendored, generated, binary, oversize, out_of_scope}

Precedence (each skipped file counted exactly once): gitignored > vendored (always-skip dir) >
generated > binary > oversize > out_of_scope (monorepo scoping).

Usage:
  python tools/exclusion_pass.py <repo_dir>
  python tools/exclusion_pass.py <repo_dir> --max-bytes 1048576 --max-lines 20000
  python tools/exclusion_pass.py <repo_dir> --scope packages/foo   # monorepo component scoping
  python tools/exclusion_pass.py <repo_dir> --json                 # machine output
"""
from __future__ import annotations

import argparse
import fnmatch
import json
import sys
from pathlib import Path

# Always-skip directories (case-insensitive, any depth) — detection.md "Always-skip directories".
ALWAYS_SKIP_DIRS = {
    "node_modules", "vendor", "bower_components", "dist", "build", "out", "target",
    ".next", ".nuxt", ".svelte-kit", "coverage", "__pycache__", ".venv", "venv",
    ".tox", ".mypy_cache", ".pytest_cache", ".gradle", ".idea", ".vscode", ".git",
    ".deepinit", ".ai", "graphify-out", ".terraform", "pods", "deriveddata",
}

# Generated / vendored / minified files (glob, case-insensitive on the name).
GENERATED_GLOBS = [
    "*.min.js", "*.min.css", "*.map", "package-lock.json", "yarn.lock", "poetry.lock",
    "Cargo.lock", "go.sum", "composer.lock", "*.generated.*", "*_pb2.py", "*.pb.go",
    "*_generated.go", "*.snap",
]
GENERATED_DIRS = {"__snapshots__"}
# header markers that flag a generated file (read the first ~40 lines)
GENERATED_HEADER_MARKERS = ("@generated", "Code generated", "DO NOT EDIT", "Auto-generated", "autogenerated")

# Binary / non-source by extension.
BINARY_EXTS = {
    ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".webp", ".svg", ".tiff",
    ".woff", ".woff2", ".ttf", ".otf", ".eot",
    ".zip", ".tar", ".gz", ".tgz", ".bz2", ".xz", ".7z", ".rar", ".jar", ".war",
    ".mp3", ".mp4", ".mov", ".avi", ".mkv", ".wav", ".flac", ".ogg",
    ".pdf", ".bin", ".wasm", ".exe", ".dll", ".so", ".dylib", ".o", ".a",
    ".class", ".pyc", ".pyo", ".lock", ".db", ".sqlite", ".dat",
}

DEFAULT_MAX_BYTES = 1_048_576       # 1 MB
DEFAULT_MAX_LINES = 20_000


def _load_gitignore(root: Path) -> list[str]:
    """Best-effort .gitignore patterns (the no-git fallback path; a real run prefers `git ls-files`)."""
    pats: list[str] = []
    gi = root / ".gitignore"
    if gi.exists():
        for raw in gi.read_text(encoding="utf-8", errors="replace").splitlines():
            line = raw.strip()
            if line and not line.startswith("#"):
                pats.append(line.rstrip("/"))
    return pats


def _matches_gitignore(rel: str, name: str, pats: list[str]) -> bool:
    for p in pats:
        if fnmatch.fnmatch(name, p) or fnmatch.fnmatch(rel, p) or fnmatch.fnmatch(rel, p + "/*"):
            return True
    return False


def _is_generated_header(path: Path) -> bool:
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            head = "".join(fh.readline() for _ in range(40))
    except Exception:  # noqa: BLE001
        return False
    return any(m in head for m in GENERATED_HEADER_MARKERS)


def classify(path: Path, root: Path, gitignore: list[str], max_bytes: int, max_lines: int,
             scope: str | None) -> str | None:
    """Return the skip CATEGORY for a file, or None if it is KEPT (in scope)."""
    rel = path.relative_to(root).as_posix()
    name = path.name
    parts_lower = [p.lower() for p in path.relative_to(root).parts]

    # 1. gitignored (the .gitignore / git ls-files contract)
    if _matches_gitignore(rel, name, gitignore):
        return "gitignored"
    # 2. vendored / always-skip directory (any depth)
    if any(seg in ALWAYS_SKIP_DIRS for seg in parts_lower[:-1]):
        return "vendored"
    # 3. generated / vendored / minified
    if any(seg in GENERATED_DIRS for seg in parts_lower[:-1]):
        return "generated"
    nl = name.lower()
    if any(fnmatch.fnmatch(nl, g.lower()) for g in GENERATED_GLOBS):
        return "generated"
    # 4. binary / non-source by extension
    if path.suffix.lower() in BINARY_EXTS:
        return "binary"
    # generated-by-header (read content) — after the cheap checks
    if path.suffix.lower() in {".ts", ".js", ".py", ".go", ".java", ".rb", ".cs", ".kt", ".php", ".rs", ".c", ".h", ".cpp"} and _is_generated_header(path):
        return "generated"
    # 5. over-size
    try:
        sz = path.stat().st_size
        if sz > max_bytes:
            return "oversize"
        if sz < 4_000_000:  # only count lines on smallish files (avoid reading a huge binary as text)
            n = sum(1 for _ in path.open("r", encoding="utf-8", errors="replace"))
            if n > max_lines:
                return "oversize"
    except Exception:  # noqa: BLE001
        pass
    # 6. monorepo scoping (component-scoped run): out of scope if not under the scope prefix
    if scope and not (rel == scope or rel.startswith(scope.rstrip("/") + "/")):
        return "out_of_scope"
    return None


def run(root: Path, max_bytes: int = DEFAULT_MAX_BYTES, max_lines: int = DEFAULT_MAX_LINES,
        scope: str | None = None) -> dict:
    gitignore = _load_gitignore(root)
    included: list[str] = []
    skipped: list[dict] = []
    counts = {k: 0 for k in ("gitignored", "vendored", "generated", "binary", "oversize", "out_of_scope")}
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        # never let the .gitignore file itself or the exclusion of the root .git pollute counts oddly:
        cat = classify(path, root, gitignore, max_bytes, max_lines, scope)
        rel = path.relative_to(root).as_posix()
        if cat is None:
            included.append(rel)
        else:
            skipped.append({"path": rel, "category": cat})
            counts[cat] += 1
    return {
        "schema": "deepinit/exclusion-pass/v1",
        "root": root.as_posix(),
        "included": sorted(included),
        "included_count": len(included),
        "skipped": sorted(skipped, key=lambda s: s["path"]),
        "skipped_count": len(skipped),
        "counts": counts,
        "thresholds": {"max_bytes": max_bytes, "max_lines": max_lines, "scope": scope},
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description="DeepInit deterministic exclusion pass (detection.md reference)")
    ap.add_argument("repo")
    ap.add_argument("--max-bytes", type=int, default=DEFAULT_MAX_BYTES)
    ap.add_argument("--max-lines", type=int, default=DEFAULT_MAX_LINES)
    ap.add_argument("--scope", default=None)
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args(argv)
    root = Path(args.repo).resolve()
    if not root.is_dir():
        print(f"ERROR: not a directory: {root}", file=sys.stderr)
        return 2
    res = run(root, args.max_bytes, args.max_lines, args.scope)
    if args.json:
        print(json.dumps(res, indent=2, ensure_ascii=False, sort_keys=True))
    else:
        print(f"included {res['included_count']} · skipped {res['skipped_count']} · counts {res['counts']}")
        for s in res["skipped"]:
            print(f"  [SKIP:{s['category']}] {s['path']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
